// Public release metadata shared by platform packaging; never reads credentials.
import {readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {resolve} from 'node:path';
const root=fileURLToPath(new URL('../',import.meta.url));
const pkg=JSON.parse(readFileSync(resolve(root,'package.json'),'utf8'));
export const version=pkg.version;
export const buildNumber=pkg.weekabooBuild;
if(!/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/.test(version)||!Number.isSafeInteger(buildNumber)||buildNumber<1||buildNumber>2100000000)throw Error('Use a numeric three-part version and a positive store build number in package.json');
export function syncAppleVersion(){
 const path=resolve(root,'ios/Version.xcconfig');
 const contents=`// Generated by scripts/release-version.mjs from package.json.\nMARKETING_VERSION = ${version}\nCURRENT_PROJECT_VERSION = ${buildNumber}\n`;
 let current;try{current=readFileSync(path,'utf8')}catch{}
 if(current!==contents)writeFileSync(path,contents);
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){syncAppleVersion();console.log(`Weekaboo ${version}, build ${buildNumber}`);}
